import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintPluginAstro from 'eslint-plugin-astro';

export default tseslint.config(
  {
    ignores: [
      'dist/',
      '.astro/',
      'node_modules/',
      'coverage/',
      'playwright-report/',
      'test-results/',
      'src/env.d.ts', // generated by `astro sync`
    ],
  },
  js.configs.recommended,
  // TypeScript parsing/rules for .ts files.
  ...tseslint.configs.recommended,
  // Astro parsing/rules for .astro files (frontmatter handled as TypeScript).
  ...eslintPluginAstro.configs.recommended,
  {
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        navigator: 'readonly',
      },
    },
  },
  // Node build scripts.
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        Buffer: 'readonly',
        process: 'readonly',
        console: 'readonly',
      },
    },
  },
);
